name: flutter_lab01_base
description: "Directorio de Estudiantes UAC - Laboratorio Integrador N.01 | SIS048 Desarrollo de Software II - 2026-I"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Navegación declarativa
  go_router: ^14.2.0

  # Consumo HTTP
  http: ^1.2.1

  # Modelos inmutables con generación de código
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # UI
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Generadores de código (ejecutar: dart run build_runner build)
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  build_runner: ^2.4.11

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
